name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure (generate compile_commands.json)
        uses: ./.github/actions/configure
        with:
          cmake-extra-args: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '22'
          style: 'file'
          tidy-checks: ''
          database: 'build/build/Release'
          ignore-tidy: 'src/VOG/Common/Test|src/VOG/Graphics/Test'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' || 'false' }}
          step-summary: true

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
